export const RESET_PASSWORD_AUTH = {
    TOKEN_LIFETIME_MINUTE: 90,
};

export const OTP_CONFIG = {
    OTP_LIFETIME_MINUTE: 5,
    OTP_LENGTH: 6,
    OTP_MAX_RETRY: 3,
    OTP_PENALTY_TIME_MINUTE: 1,
    OTP_DEV_VALUE: '666666',
    OTP_COUNTDOWN_TIME: 2
};
